#!/usr/bin/env python3
"""
ML Anomaly Detector — Real-time Intrusion Detection (Config C)
Reference: Khan (2016) Case Study — Phase 3, Hybrid ML-IDPS

Implements lightweight Isolation Forest and Random Forest classifiers
for sub-50ms detection latency on network flow features.

Architecture:
  1. Reads Suricata eve.json logs in real-time
  2. Extracts flow features via FeaturePipeline
  3. Classifies traffic as benign/attack using trained model
  4. Issues iptables drop commands for high-confidence attacks

Models used:
  - Isolation Forest: Unsupervised anomaly detection (faster)
  - Random Forest: Supervised classification (higher accuracy)

Target latency: <50ms per flow classification
"""

import argparse
import json
import os
import sys
import time
import threading
import socket
import subprocess
import numpy as np
import pandas as pd
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from collections import defaultdict, deque
from dataclasses import dataclass, field

try:
    from sklearn.ensemble import IsolationForest, RandomForestClassifier
    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import classification_report, confusion_matrix

    HAS_SKLEARN = True
except ImportError:
    HAS_SKLEARN = False

try:
    import joblib

    HAS_JOBLIB = True
except ImportError:
    HAS_JOBLIB = False


# ─────────────────────────────────────────────────────────────
# Data Structures
# ─────────────────────────────────────────────────────────────
@dataclass
class FlowFeature:
    """Single flow feature record for ML classification."""

    flow_id: str
    timestamp: float
    duration_ms: float
    total_fwd_pkts: int
    total_bwd_pkts: int
    total_pkts: int
    flow_bytes_per_sec: float
    flow_packets_per_sec: float
    pkt_len_mean: float
    pkt_len_std: float
    flag_syn: int
    flag_ack: int
    flag_fin: int
    flag_rst: int
    flag_psh: int
    flag_urg: int
    label: str = "benign"  # benign, attack, unknown
    confidence: float = 0.0
    prediction: str = "unknown"
    detection_time_ms: float = 0.0


@dataclass
class DetectionAlert:
    """Alert generated by ML detector."""

    alert_id: str
    flow_id: str
    attack_category: str  # A1, A2, A4
    severity: str  # low, medium, high, critical
    confidence: float
    detection_time: float
    feature_vector: Dict
    action_taken: str = "none"
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


# ─────────────────────────────────────────────────────────────
# Model Trainer
# ─────────────────────────────────────────────────────────────
class ModelTrainer:
    """Trains and persists ML models for intrusion detection."""

    FEATURE_COLUMNS = [
        "duration_ms",
        "total_pkts",
        "flow_bytes_per_sec",
        "flow_packets_per_sec",
        "pkt_len_mean",
        "pkt_len_std",
        "flag_syn",
        "flag_ack",
        "flag_fin",
        "flag_rst",
        "flag_psh",
        "flag_urg",
    ]

    def __init__(self, model_type: str = "isolation_forest"):
        self.model_type = model_type
        self.scaler = StandardScaler()
        self.model = self._build_model()
        self.is_trained = False

    def _build_model(self):
        """Build the selected ML model."""
        if self.model_type == "isolation_forest":
            return IsolationForest(
                n_estimators=100,
                contamination=0.1,
                max_samples="auto",
                random_state=42,
                n_jobs=-1,
            )
        elif self.model_type == "random_forest":
            return RandomForestClassifier(
                n_estimators=100,
                max_depth=10,
                min_samples_split=5,
                random_state=42,
                n_jobs=-1,
            )
        elif self.model_type == "hybrid":
            return {
                "isolation": IsolationForest(contamination=0.1, random_state=42),
                "classifier": RandomForestClassifier(n_estimators=50, random_state=42),
            }
        else:
            raise ValueError(f"Unknown model type: {self.model_type}")

    def train(self, X: np.ndarray, y: Optional[np.ndarray] = None):
        """Train the model on feature data."""
        X_scaled = self.scaler.fit_transform(X)

        if self.model_type == "hybrid":
            self.model["isolation"].fit(X_scaled)
            # Use isolation forest predictions as pseudo-labels for supervised training
            pseudo_labels = self.model["isolation"].predict(X_scaled)
            pseudo_labels = np.where(
                pseudo_labels == -1, 1, 0
            )  # -1=attack, 1=benign → 1=attack, 0=benign
            self.model["classifier"].fit(X_scaled, pseudo_labels)
        elif self.model_type == "isolation_forest":
            self.model.fit(X_scaled)
        else:
            if y is None:
                raise ValueError("Random Forest requires labeled data")
            self.model.fit(X_scaled, y)

        self.is_trained = True
        print(f"[TRAINER] {self.model_type} model trained on {X.shape[0]} samples")

    def predict(self, X: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        """Predict on feature matrix. Returns (predictions, confidence scores)."""
        X_scaled = self.scaler.transform(X)

        if self.model_type == "isolation_forest":
            preds = self.model.predict(X_scaled)
            scores = self.model.score_samples(X_scaled)
            # Convert: -1=anomaly(attack), 1=benign → 1=attack, 0=benign
            preds = np.where(preds == -1, 1, 0)
            # Confidence from anomaly score (more negative = more anomalous)
            confidence = np.abs(scores)
            confidence = (confidence - confidence.min()) / (
                confidence.max() - confidence.min() + 1e-8
            )
            return preds, confidence

        elif self.model_type == "hybrid":
            iso_preds = self.model["isolation"].predict(X_scaled)
            clf_preds = self.model["classifier"].predict(X_scaled)
            clf_probs = self.model["classifier"].predict_proba(X_scaled)
            # Use hybrid: isolation forest for initial detection, RF for confidence
            combined_preds = np.where(iso_preds == -1, 1, clf_preds)
            confidence = clf_probs.max(axis=1)
            return combined_preds, confidence
        else:
            preds = self.model.predict(X_scaled)
            if hasattr(self.model, "predict_proba"):
                confidence = self.model.predict_proba(X_scaled).max(axis=1)
            else:
                confidence = np.ones(len(preds))
            return preds, confidence

    def save(self, path: str):
        """Save trained model and scaler."""
        os.makedirs(os.path.dirname(path), exist_ok=True)
        model_data = {
            "model_type": self.model_type,
            "scaler": self.scaler,
            "model": self.model,
            "is_trained": self.is_trained,
        }
        joblib.dump(model_data, path)
        print(f"[TRAINER] Model saved to {path}")

    def load(self, path: str):
        """Load trained model and scaler."""
        model_data = joblib.load(path)
        self.model_type = model_data["model_type"]
        self.scaler = model_data["scaler"]
        self.model = model_data["model"]
        self.is_trained = model_data["is_trained"]
        print(f"[TRAINER] Model loaded from {path}")


# ─────────────────────────────────────────────────────────────
# Real-time ML Detector Daemon
# ─────────────────────────────────────────────────────────────
class MLDetectorDaemon:
    """
    Real-time anomaly detection daemon.
    Reads Suricata eve.json, classifies flows, and takes action.
    """

    def __init__(
        self,
        model_path: str = None,
        model_type: str = "isolation_forest",
        eve_json_path: str = "data/suricata/eve.json",
        threshold: float = 0.7,
        action: str = "block",
    ):
        self.eve_json_path = eve_json_path
        self.threshold = threshold
        self.action = action
        self._lock = threading.Lock()
        self._running = False

        # Initialize model
        self.trainer = ModelTrainer(model_type=model_type)
        if model_path and os.path.exists(model_path):
            self.trainer.load(model_path)

        # Detection state
        self.alerts: List[DetectionAlert] = []
        self.flow_buffer = deque(maxlen=10000)
        self.stats = defaultdict(int)
        self._alert_id_counter = 0

        # Feature tracking for real-time classification
        self.recent_features = deque(maxlen=1000)

    def parse_eve_json(self, line: str) -> Optional[Dict]:
        """Parse a single line of Suricata eve.json."""
        try:
            event = json.loads(line.strip())
            return event
        except json.JSONDecodeError:
            return None

    def extract_features_from_event(self, event: Dict) -> Optional[FlowFeature]:
        """Extract flow features from Suricata eve.json event."""
        try:
            if event.get("event_type") != "flow":
                return None

            flow = event.get("flow", {})
            feature = FlowFeature(
                flow_id=flow.get("flow_id", ""),
                timestamp=event.get("timestamp", time.time()),
                duration_ms=flow.get("duration", 0) * 1000,
                total_fwd_pkts=flow.get("pkts_toserver", 0),
                total_bwd_pkts=flow.get("pkts_toclient", 0),
                total_pkts=flow.get("pkts_toserver", 0) + flow.get("pkts_toclient", 0),
                flow_bytes_per_sec=flow.get("bytes_toserver", 0)
                + flow.get("bytes_toclient", 0),
                flow_packets_per_sec=0,  # Calculated below
                pkt_len_mean=0,
                pkt_len_std=0,
                flag_syn=flow.get("syn_count", 0),
                flag_ack=flow.get("ack_count", 0),
                flag_fin=flow.get("fin_count", 0),
                flag_rst=flow.get("rst_count", 0),
                flag_psh=flow.get("psh_count", 0),
                flag_urg=flow.get("urg_count", 0),
            )

            # Calculate derived features
            elapsed = max(feature.duration_ms / 1000, 0.001)
            feature.flow_packets_per_sec = feature.total_pkts / elapsed
            if feature.duration_ms > 0:
                feature.flow_bytes_per_sec = (
                    flow.get("bytes_toserver", 0) + flow.get("bytes_toclient", 0)
                ) / elapsed

            return feature
        except Exception:
            return None

    def classify_flow(self, feature: FlowFeature) -> Tuple[str, float, str]:
        """
        Classify a single flow using the trained model.
        Returns: (prediction, confidence, attack_category)
        """
        if not self.trainer.is_trained:
            return "unknown", 0.0, "unknown"

        feature_vector = np.array(
            [
                [
                    feature.duration_ms,
                    feature.total_pkts,
                    feature.flow_bytes_per_sec,
                    feature.flow_packets_per_sec,
                    feature.pkt_len_mean,
                    feature.pkt_len_std,
                    feature.flag_syn,
                    feature.flag_ack,
                    feature.flag_fin,
                    feature.flag_rst,
                    feature.flag_psh,
                    feature.flag_urg,
                ]
            ]
        )

        preds, confidence = self.trainer.predict(feature_vector)
        pred = int(preds[0])
        conf = float(confidence[0])

        # Determine attack category based on feature patterns
        attack_category = self._categorize_attack(feature)

        if pred == 1 and conf >= self.threshold:
            return "attack", conf, attack_category
        elif pred == 1:
            return "suspicious", conf, attack_category
        else:
            return "benign", conf, "normal"

    def _categorize_attack(self, feature: FlowFeature) -> str:
        """Categorize attack type based on feature patterns."""
        # Heuristic categorization based on flow characteristics
        if feature.flag_syn > feature.flag_ack * 5 and feature.total_fwd_pkts > 100:
            return "A1a"  # Port scan
        if feature.flag_syn > 100 and feature.total_fwd_pkts > 500:
            return "A1"  # DoS flood
        if (
            feature.flag_syn > 0
            and feature.flag_ack == 0
            and feature.total_fwd_pkts < 5
        ):
            return "A4c"  # XSS/SQLi reconnaissance
        if feature.flow_bytes_per_sec > 1000000 and feature.total_fwd_pkts > 1000:
            return "A2d"  # Resource abuse
        return "A4"  # Default application attack

    def take_action(self, alert: DetectionAlert):
        """Take enforcement action (block IP via iptables)."""
        if self.action == "block":
            try:
                src_ip = alert.feature_vector.get("src_ip", "")
                if src_ip:
                    subprocess.run(
                        ["iptables", "-A", "INPUT", "-s", src_ip, "-j", "DROP"],
                        capture_output=True,
                        timeout=5,
                    )
                    alert.action_taken = f"blocked {src_ip}"
            except Exception as e:
                alert.action_taken = f"failed: {e}"
        elif self.action == "alert":
            alert.action_taken = "logged_only"
        elif self.action == "rate_limit":
            alert.action_taken = "rate_limited"

    def process_event(self, event: Dict) -> Optional[DetectionAlert]:
        """
        Process a single Suricata event end-to-end.
        Returns DetectionAlert if attack detected, None otherwise.
        """
        feature = self.extract_features_from_event(event)
        if feature is None:
            return None

        start = time.time()
        prediction, confidence, category = self.classify_flow(feature)
        feature.detection_time_ms = (time.time() - start) * 1000

        if prediction in ("attack", "suspicious"):
            self._alert_id_counter += 1
            alert = DetectionAlert(
                alert_id=f"ML-{self._alert_id_counter:06d}",
                flow_id=feature.flow_id,
                attack_category=category,
                severity=self._severity_from_confidence(confidence),
                confidence=confidence,
                detection_time=feature.detection_time_ms,
                feature_vector=feature.__dict__,
                timestamp=datetime.now().isoformat(),
            )

            if self.action != "none":
                self.take_action(alert)

            self.alerts.append(alert)
            self.stats["total_detections"] += 1

            if prediction == "attack":
                self.stats["confirmed_attacks"] += 1
            else:
                self.stats["suspicious_alerts"] += 1

            # Track latency
            if feature.detection_time_ms > 50:
                self.stats["latency_violations"] += 1

            return alert

        self.stats["benign_classified"] += 1
        return None

    def _severity_from_confidence(self, confidence: float) -> str:
        """Map confidence to severity level."""
        if confidence >= 0.9:
            return "critical"
        elif confidence >= 0.7:
            return "high"
        elif confidence >= 0.5:
            return "medium"
        else:
            return "low"

    def start(self, eve_json_path: str = None, batch_size: int = 100):
        """Start monitoring Suricata eve.json."""
        self._running = True
        self.eve_json_path = eve_json_path or self.eve_json_path

        print(
            f"[ML DETECTOR] Starting daemon (model: {self.trainer.model_type}, "
            f"threshold: {self.threshold})"
        )

        while self._running:
            if not os.path.exists(self.eve_json_path):
                time.sleep(1)
                continue

            try:
                with open(self.eve_json_path, "r") as f:
                    lines = f.readlines()

                for line in lines[-batch_size:]:
                    if not self._running:
                        break
                    event = self.parse_eve_json(line)
                    if event:
                        self.process_event(event)

                time.sleep(0.1)  # Polling interval

            except Exception as e:
                print(f"[ERROR] {e}", file=sys.stderr)
                time.sleep(1)

    def stop(self):
        """Stop the daemon."""
        self._running = False
        print(f"[ML DETECTOR] Stopped. Stats: {dict(self.stats)}")

    def get_detection_stats(self) -> Dict:
        """Return detection statistics."""
        total = self.stats.get("total_detections", 0)
        return {
            "total_detections": total,
            "confirmed_attacks": self.stats.get("confirmed_attacks", 0),
            "suspicious_alerts": self.stats.get("suspicious_alerts", 0),
            "benign_classified": self.stats.get("benign_classified", 0),
            "latency_violations": self.stats.get("latency_violations", 0),
            "avg_detection_latency_ms": (
                sum(a.detection_time_ms for a in self.alerts) / len(self.alerts)
                if self.alerts
                else 0
            ),
            "total_alerts": len(self.alerts),
        }

    def generate_report(self) -> Dict:
        """Generate comprehensive detection report."""
        stats = self.get_detection_stats()
        return {
            "report_timestamp": datetime.now().isoformat(),
            "model_type": self.trainer.model_type,
            "total_alerts": len(self.alerts),
            "statistics": stats,
            "alerts": [a.__dict__ for a in self.alerts[-100:]],  # Last 100
        }


# ─────────────────────────────────────────────────────────────
# Training Data Generator (for demo/testing with CIC-IDS2018 format)
# ─────────────────────────────────────────────────────────────
class SyntheticDataGenerator:
    """Generate synthetic training data matching CIC-IDS2018/NSL-KDD features."""

    @staticmethod
    def generate_benign_flows(n: int = 10000) -> np.ndarray:
        """Generate normal traffic flow features."""
        features = []
        for _ in range(n):
            duration = np.random.exponential(100)
            fwd_pkts = np.random.poisson(50)
            bwd_pkts = np.random.poisson(30)
            bytes_sec = np.random.normal(10000, 2000)
            pkt_sec = np.random.normal(80, 20)
            pkt_len_mean = np.random.normal(500, 100)
            pkt_len_std = np.random.exponential(50)
            flags = [
                np.random.poisson(1),
                np.random.poisson(5),
                np.random.poisson(0.5),
                np.random.poisson(0.1),
                np.random.poisson(0.3),
                np.random.poisson(0.05),
            ]
            features.append(
                [
                    duration,
                    fwd_pkts + bwd_pkts,
                    bytes_sec,
                    pkt_sec,
                    pkt_len_mean,
                    pkt_len_std,
                ]
                + flags
            )
        return np.array(features)

    @staticmethod
    def generate_attack_flows(n: int = 1000) -> np.ndarray:
        """Generate attack traffic flow features."""
        features = []
        for _ in range(n):
            attack_type = np.random.choice(["port_scan", "dos", "sqli", "xss"])
            if attack_type == "port_scan":
                duration = np.random.uniform(1, 5)
                fwd_pkts = np.random.randint(100, 1000)
                bwd_pkts = 0
                bytes_sec = np.random.normal(5000, 1000)
                flags = [np.random.randint(50, 200), 0, 0, 0, 0, 0]
            elif attack_type == "dos":
                duration = np.random.uniform(1, 30)
                fwd_pkts = np.random.randint(500, 5000)
                bwd_pkts = 0
                bytes_sec = np.random.normal(50000, 10000)
                flags = [np.random.randint(100, 500), 0, 0, 0, 0, 0]
            else:
                duration = np.random.exponential(5)
                fwd_pkts = np.random.randint(1, 10)
                bwd_pkts = np.random.randint(1, 10)
                bytes_sec = np.random.normal(2000, 500)
                flags = [1, 5, 1, 0, 0, 0]

            pkt_sec = fwd_pkts / max(duration, 0.001)
            pkt_len_mean = np.random.normal(300, 50)
            pkt_len_std = np.random.exponential(30)
            features.append(
                [
                    duration,
                    fwd_pkts + bwd_pkts,
                    bytes_sec,
                    pkt_sec,
                    pkt_len_mean,
                    pkt_len_std,
                ]
                + flags
            )
        return np.array(features)

    @classmethod
    def generate_dataset(
        cls, n_benign=10000, n_attack=1000
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Generate full training dataset."""
        benign = cls.generate_benign_flows(n_benign)
        attack = cls.generate_attack_flows(n_attack)

        X = np.vstack([benign, attack])
        y = np.array([0] * n_benign + [1] * n_attack)  # 0=benign, 1=attack

        # Shuffle
        indices = np.arange(len(X))
        np.random.shuffle(indices)
        return X[indices], y[indices]


# ─────────────────────────────────────────────────────────────
# CLI Entry Point
# ─────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="ML Anomaly Detector — Hybrid IDS (Config C)"
    )
    parser.add_argument(
        "--mode",
        choices=["train", "detect", "demo"],
        default="demo",
        help="Operating mode",
    )
    parser.add_argument(
        "--model-path",
        default="ml/models/idps_model.joblib",
        help="Path to trained model",
    )
    parser.add_argument(
        "--eve-json", default="data/suricata/eve.json", help="Suricata eve.json path"
    )
    parser.add_argument(
        "--threshold", type=float, default=0.7, help="Detection confidence threshold"
    )
    parser.add_argument(
        "--model-type",
        choices=["isolation_forest", "random_forest", "hybrid"],
        default="isolation_forest",
        help="ML model type",
    )
    parser.add_argument(
        "--train-samples", type=int, default=11000, help="Number of training samples"
    )
    parser.add_argument(
        "--output",
        default="data/results/ml_detection_report.json",
        help="Output report path",
    )

    args = parser.parse_args()

    if args.mode == "train":
        print("[ML DETECTOR] Training model...")
        X, y = SyntheticDataGenerator.generate_dataset(
            n_benign=args.train_samples // 10, n_attack=args.train_samples // 10
        )
        trainer = ModelTrainer(model_type=args.model_type)
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )
        trainer.train(X_train, y_train)

        # Evaluate
        preds, confs = trainer.predict(X_test)
        print(f"[ML DETECTOR] Test accuracy: {(preds == y_test).mean():.4f}")
        print(f"[ML DETECTOR] Classification report:")
        print(classification_report(y_test, preds))

        trainer.save(args.model_path)

    elif args.mode == "detect":
        detector = MLDetectorDaemon(
            model_path=args.model_path,
            model_type=args.model_type,
            eve_json_path=args.eve_json,
            threshold=args.threshold,
        )
        if os.path.exists(args.model_path):
            detector.trainer.load(args.model_path)
        detector.start()

    elif args.mode == "demo":
        print("[ML DETECTOR] Running demo with synthetic data...")
        X, y = SyntheticDataGenerator.generate_dataset()
        trainer = ModelTrainer(model_type=args.model_type)
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )
        trainer.train(X_train, y_train)

        # Benchmark latency
        latencies = []
        for i in range(min(100, len(X_test))):
            start = time.time()
            preds, confs = trainer.predict(X_test[i : i + 1])
            latencies.append((time.time() - start) * 1000)

        avg_latency = np.mean(latencies)
        p95_latency = np.percentile(latencies, 95)
        p99_latency = np.percentile(latencies, 99)

        print(f"\n[ML DETECTOR] Performance Benchmark:")
        print(f"  Average latency: {avg_latency:.2f}ms")
        print(f"  P95 latency:     {p95_latency:.2f}ms")
        print(f"  P99 latency:     {p99_latency:.2f}ms")
        print(f"  Target (<50ms):  {'PASS ✓' if avg_latency < 50 else 'FAIL ✗'}")

        accuracy = (preds == y_test).mean()
        print(f"\n[ML DETECTOR] Model Accuracy: {accuracy:.4f}")
        print(f"  Model Type: {args.model_type}")
        print(f"  Training Samples: {len(X_train)}")
        print(f"  Test Samples: {len(X_test)}")

        # Save report
        report = {
            "model_type": args.model_type,
            "avg_latency_ms": round(avg_latency, 2),
            "p95_latency_ms": round(p95_latency, 2),
            "p99_latency_ms": round(p99_latency, 2),
            "accuracy": round(accuracy, 4),
            "target_latency_met": avg_latency < 50,
            "training_samples": len(X_train),
            "test_samples": len(X_test),
            "timestamp": datetime.now().isoformat(),
        }
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        with open(args.output, "w") as f:
            json.dump(report, f, indent=2)
        print(f"\n[ML DETECTOR] Report saved to {args.output}")


if __name__ == "__main__":
    main()
